name: nlp2
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.10.12
  - pip:
      - faiss-cpu==1.7.4
      - torch==2.0.1
      - ir-measures==0.3.3
      - jupyter==1.0.0
      - pytest==7.4.0
      - tokenizers==0.13.3
      - transformers==4.30.0
      - datasets==2.16.1 
      - numpy>=1.24.0 