#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=blip2_repr_test
#SBATCH --output=logs/blip2_compute_rsa_%j.out
#SBATCH --error=logs/blip2_compute_rsa_%j.err
#SBATCH --time=00:06:00
#SBATCH --cpus-per-task=4

# === Load Modules ===
module purge
module load 2024
module load Anaconda3/2024.06-1

# === Activate Conda Environment ===
source activate vlm_env
# === Run the script ===
srun python $HOME/NLP2_project/VLM/compute_vlm_rsa.py




