name: vlm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - transformers
  - pillow
  - pip:
    - huggingface_hub  # Hugging Face hub for model caching
